@startuml

left to right direction

管理员 as admin

rectangle 任务仪表盘界面 {
    usecase (新建项目) as create_project
    usecase (选择待标注模型) as choose_model
    usecase (选择目标关节) as choose_target_joints
    create_project ..> choose_model : <<include>>
    create_project ..> choose_target_joints : <<include>>

    note top of choose_target_joints : pivot 关节必选

    usecase (查看所有项目) as view_projects
    usecase (选择当前项目) as choose_project
    usecase (查看当前项目的状态) as view_project_status
    view_projects ..> choose_project : <<include>>
    view_projects ..> view_project_status : <<include>>

    usecase (新建标注任务) as create_task
    usecase (分配任务给标注人员) as assign_task
    create_task ..> assign_task : <<include>>
    usecase (验收待验证的标注任务) as check_task
}

admin -- create_project
admin -- view_projects
admin -- create_task
admin -- check_task

@enduml