@startuml

left to right direction

标注人员 as tagger

rectangle 标注页面 {
    usecase (查看标注界面) as view_label_interface
    usecase (查看参考图片) as view_ref_image
    usecase (实时查看模型姿态) as view_model_pose
    view_label_interface ..> view_ref_image : <<include>>
    view_label_interface ..> view_model_pose : <<include>>

    usecase (选择当前关节) as choose_active_joint
    usecase (调整关节旋转) as control_rotation
    choose_active_joint ..> control_rotation : <<include>>

    usecase (保存当前帧对应数据) as save_current_frame
    usecase (切换至相邻帧) as change_neighbor_frames

}

tagger -- view_label_interface
tagger -- choose_active_joint
tagger -- save_current_frame
tagger -- change_neighbor_frames

@enduml